name: co2_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy<2.0
  - scikit-learn<1.6
  - matplotlib
  - seaborn
  - jupyter
  - xgboost
  - catboost
  - shap